[package]
name = "hello-ratatui"
version = "0.1.0"
description = "simplate template test"
authors = ["Zoltan Karahuta <zoltan.karahuta@indisemi.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
